# Install the apt prerequisites
# addons:
#   apt:
#     packages:
#       - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - chmod +x bin/hugo
  - cd src
  - ../bin/hugo
  - cd public 

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  verbose: true
  target-branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
