---
baseURL: "https://sblack.rocks"
languageCode: "en-us"
title: "Steven Black"
paginate: 10
canonifyurls: true
theme: "minimal"
enableGitInfo: true
googleAnalytics: "G-TKBEKCXVEC"

deployment:
  targets:
    name: s3
    cloudFrontDistributionID: "E6V2C29GOA16F"
    URL: "s3://784384215106-us-east-1-website-sblackdotrocks?region=us-east-1"

permalinks:
  post: /:year/:month/:title/

params:
  description: "Welcome to the Internet"
  author: "Steven Black"
  githubUsername: "sblack4"
  profilePic: /img/happy.jpeg
  SidebarRecentLimit: 5
  accent: "red"
  showBorder: true
  backgroundColor: "white"
  font: "Raleway" # should match the name on Google Fonts!
  highlight: true
  highlightStyle: "solarized-dark" #TODO:(sblack4) figure this out! I want dark theme <3
  highlightLanguages: ["python", "shell"]

menu: 
  main:
    - url: "/"
      name: "home"
      weight: 1
    - url: "/changelog"
      name: "changelog"
      weight: 3
    # - url: "/projects"
    #   name: "projects"
    #   weight: 3
    # - url: "https://blog.sblack.rocks"
    #   name: "blog"
    #   weight: 5
  icon: 
    - url: "mailto:sblack.rocks@gmail.com"
      name: "envelope-o"
      weight: 1
    - url: "https://github.com/sblack4"
      name: "github"
      weight: 2
    - url: "https://stackoverflow.com/users/5568528/steven-black"
      name: "stack-overflow"
      weight: 3
    # - url: "https://twitter.com/Genseb7"
    #   name: "twitter"
    #   weight: 4
    - url: "https://www.linkedin.com/in/steven-black/"
      name: "linkedin"
      weight: 5
    - url: "https://medium.com/@sblack4"
      name: "medium"
      weight: 6
    # - url: "/blog/index.xml"
    #   name: "rss-square"
    #   weight: 7
--- 