on:
  schedule:
  - cron: '0 0 1 * *'
  workflow_dispatch:

name: Check markdown links
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'
          # extended: true
          
      - name: Build
        run: |
          cd src
          hugo --minify
          
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --verbose --no-progress src/public/**/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
#       - name: Create Issue From File
#         uses: peter-evans/create-issue-from-file@v3
#         with:
#           title: Link Checker Report
#           content-filepath: ./lychee/out.md
#           labels: report, automated issue
